name: Docker Image CI

on:
  workflow_run:
    workflows: ['Gradle Build']
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Download BootJar
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: gradle.yml
        workflow_conclusion: success
        path: build/libs
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_LOGIN }}
        password: ${{ secrets.DOCKER_PASS }}
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: copysiper/shortinator-backend:latest
